# vi: set ft=ruby :

vhosts =[
  { :hostname => "iac-client01",
    :fssh_port => "2270",
    :fweb_port => "8070",
    :box => "bento/ubuntu-20.04",
    :ip =>"10.10.100.200",
    :profile => "microk8",
    :memory => "1024"},
    { :hostname => "iac-client02",
    :fssh_port => "2271",
    :fweb_port => "8071",
    :box => "bento/ubuntu-20.04",
    :ip =>"10.10.100.201",
    :profile => "microk8",
    :memory => "1024"},
    { :hostname => "iac-nginx-lb",
    :fssh_port => "2272",
    :fweb_port => "8072",
    :box => "bento/ubuntu-20.04",
    :ip =>"10.10.100.202",
    :profile => "microk8",
    :memory => "1024"},
    { :hostname => "iac-web01",
    :fssh_port => "2273",
    :fweb_port => "8073",
    :box => "bento/ubuntu-20.04",
    :ip =>"10.10.100.203",
    :profile => "microk8",
    :memory => "1024"},
    { :hostname => "iac-web02",
    :fssh_port => "2274",
    :fweb_port => "8074",
    :box => "bento/ubuntu-20.04",
    :ip =>"10.10.100.204",
    :profile => "microk8",
    :memory => "1024"},
    { :hostname => "iac-web03",
    :fssh_port => "2275",
    :fweb_port => "8075",
    :box => "bento/ubuntu-20.04",
    :ip =>"10.10.100.205",
    :profile => "microk8",
    :memory => "1024"},

]

Vagrant.configure("2") do |config|

  vhosts.each do |vhost|

    config.vm.define vhost[:hostname] do |node|
      node.vm.box = vhost[:box]
      node.vm.hostname = vhost[:hostname]
      node.vm.box_url = vhost[:box]
      node.vm.boot_timeout = 3600
      node.vm.network :private_network, ip: vhost[:ip], virtualbox__intnet: true
      node.vm.network :forwarded_port, id:"iac 01", guest:22, host: vhost[:fssh_port], host_ip: "127.0.0.1", auto_correct: true
      node.vm.network :forwarded_port, id:"iac 02", guest:8072, host: vhost[:fweb_port], host_ip: "127.0.0.1", auto_correct: true

      node.vm.provider :virtualbox do |v|
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        v.customize ["modifyvm", :id, "--memory", vhost[:memory]]
        v.customize ["modifyvm", :id, "--name", vhost[:hostname]]
        v.customize ["modifyvm", :id, "--cpus", 2]
      end
      node.vm.provision :shell, path: "./bootstrap.sh"
      #node.vm.provision :shell, inline: "sudo apt-get update ; sudo apt-get install python3-pip -y; sudo pip3 install ansible"
      #node.vm.provision :shell, inline: "sudo ansible-playbook -i localhost /vagrant/playbook.yaml"
    end
  end

end
