# -*- mode: ruby -*-
# vi: set ft=ruby :

# variaveis

  vhosts =[
    { :hostname => "infra-as-code-br", :box => "bento/ubuntu-18.04", :ip =>"10.10.10.100", :memory => "1024"},
    { :hostname => "bo",               :box => "minimal/centos6",    :ip =>"10.10.10.101", :memory => "256"},
    { :hostname => "stretch",          :box => "minimal/centos7",    :ip =>"10.10.10.102", :memory => "256"},
    { :hostname => "jessie",           :box => "minimal/centos7",    :ip =>"10.10.10.103", :memory => "512"},
    { :hostname => "squeeze",          :box => "minimal/centos6",    :ip =>"10.10.10.104", :memory => "256"},
    { :hostname => "etch",             :box => "minimal/xenial64",   :ip =>"10.10.10.105", :memory => "256"},
    { :hostname => "sarge",            :box => "minimal/centos6",    :ip =>"10.10.10.106", :memory => "512"},
    { :hostname => "slink",            :box => "minimal/centos7",    :ip =>"10.10.10.107", :memory => "256"},
    { :hostname => "woody",            :box => "minimal/xenial64",   :ip =>"10.10.10.108", :memory => "512"},
    { :hostname => "potato",           :box => "minimal/trusty64",   :ip =>"10.10.10.109", :memory => "256"},
    { :hostname => "rex",              :box => "minimal/centos6",    :ip =>"10.10.10.110", :memory => "512"},
  ]

Vagrant.configure("2") do |config|
 
  vhosts.each do |vhost|
    
    config.vm.define vhost[:hostname] do |node|
      node.vm.box = vhost[:box]
      node.vm.hostname = vhost[:hostname]
      node.vm.box_url = vhost[:box]
      node.vm.boot_timeout = 3600
      node.vm.network :private_network, ip: vhost[:ip], virtualbox__intnet: true
      node.vm.provider :virtualbox do |v|
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        v.customize ["modifyvm", :id, "--memory", vhost[:memory]]
        v.customize ["modifyvm", :id, "--name", vhost[:hostname]]
      end
      if vhost[:hostname] == "infra-as-code-br"
        node.vm.provision "shell",
          inline: "sudo apt update ; sudo apt install python-pip sshpass -y ; cp /vagrant/hosts.ini /home/vagrant/hosts.ini"
      end
    end
  end
end
