apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-iac
  name: pod-iac
spec:
  containers:
  - image: nginx
    name: pod-iac
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
