---
apiVersion: v1
kind: Service
metadata:
  name: nginx-infraascode
  namespace: infraascode
spec:
  selector:
    app: nginx-infraascode
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
